### ISSUE TITLE
Svg.Geometry.translateBy causes Svg to disappear

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-geometry-svg#10]
Transforming an Svg element with `translateBy` causes the Svg to no longer appear.

This occurs on the latest versions of Firefox and Chrome.
[Ellie example](https://ellie-app.com/4jPJ27LdYRha1)

**Comment by MartinSStewart** [comment]
This issue can be worked around by wrapping the `translateBy` result in another Svg element.

**Comment by ianmackenzie** [comment]
The issue here is a mismatch between SVG and HTML elements:

  - Things like `<polyline>` and `<g>` (group) are _SVG_ elements
  - They must go inside an `<svg>`, which is itself an _HTML_ element

The Ellie example you gave has

```elm
Svg.svg [] [ drawSvg ]
    |> Geometry.Svg.translateBy
        (Vector2d.fromComponents ( 0, 0 ))
```

which results in something like

```html
<body>
  <g transform="translate(0 0)">
    <svg>
      <polyline points="..." stroke=...></polyline>
    </svg>
  </g>
</body>
```

which has `<polyline>` (an SVG element) inside `<svg>` (an HTML element) inside `<g>` (an SVG element) inside `<body>` (an HTML element). If you change your Ellie example to

```elm
Svg.svg []
    [ drawSvg
        |> Geometry.Svg.translateBy
            (Vector2d.fromComponents ( 0, 0 ))
    ]
```

(that is, apply `translateBy` to `drawSvg`, not the `Svg.svg` call) then you get

```html
<body>
  <svg>
    <g transform="translate(0 0)">
      <polyline points="..." stroke=...></polyline>
    </g>
  </svg>
</body>
```

which works - the `<svg>` is an HTML element, and the `<g>` and `<polyline>` within it are SVG elements.

You can actually see this in the type signatures of the various functions:

```elm
Svg.svg : List (Attribute msg) -> List (Svg msg) -> Html msg
Geometry.Svg.polyline : List (Attribute msg) -> Polyline2d -> Svg msg
Geometry.Svg.translateBy : Vector2d -> Svg msg -> Svg msg
```

That is:

  - `Svg.svg` takes a list of `Svg msg` values and produces an `Html msg` value
  - `Geometry.Svg.polyline` produces an `Svg msg` value
  - `Geometry.Svg.translateBy` takes an `Svg msg` value and translates it

This means that it's not correct to use `Geometry.Svg.translateBy` on the result of `Svg.svg` - `translateBy` works on `Svg msg` values, not `Html msg` ones! Unfortunately this is a type error that the compiler cannot catch, since `Html msg` and `Svg msg` are actually just both type aliases for the same `VirtualDom.Node msg` type.

I'll add a note to the transformation docs to point out that they cannot be used on a top-level `<svg>` element, but I'm not sure how else this can be addressed. Does that make sense?

**Comment by MartinSStewart** [comment]
Thank you for the detail explanation, I understand what's going on now. 

Could this be prevented by having transform functions always add an extra svg tag around the transform tag? I'm not sure if this causes other things to not work or hurts performance.

Adding a note to the documentation is a good idea.

Thanks again for your help!
