### ISSUE TITLE
Specify units for geometry functions

### ISSUE THREAD

**Issue by pravdomil** [ianmackenzie/elm-geometry-svg#18]
Hello,
I'm having hard time to work with units and elm-geometry-svg.
My units gets mismatched.
What about forcing `Pixels.Pixels` as units?

Everything else works great though!

**Comment by ianmackenzie** [comment]
Hi @pravdomil,

I agree that getting units right with SVG is annoying, but I was reluctant to enforce `Pixels` as the unit for `elm-geometry-svg` functions since sometimes you do want to draw in other units and then use a scaling factor at a higher level (on a top-level `Svg.g`, for example) to convert everything to pixels for display.

I've actually been working on https://github.com/ianmackenzie/elm-2d-drawing which has full support for units (you can freely combine pixels and real-world units in a nice flexible but type-safe way) as well as nicer abstractions for a lot of SVG functionality (transformations, gradients etc.). I've been using it at my job for a while and it's been working well, 'just' need to finish documenting/polishing it for release. So I think I'm tempted to leave `elm-geometry-svg` as-is as a kind of low-level/interop package, and have `elm-2d-drawing` be the high-level/type-safe/units-safe option. Does that make sense?

**Comment by pravdomil** [comment]
that would be great, looking forward to use elm-2d-drawing, feel free to close the issue, if you wnat
